restart_file: fcre-2020-11-01-GLM_2.nc
start_datetime: 2020-11-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2020-11-08 00:00:00
forecast_horizon: '14'
sim_name: GLM_2
configure_flare: configure_flare_GLM.yml
configure_obs: observation_processing.yml
use_s3: yes
