restart_file: /home/rstudio/FCRE-forecast-code/forecasts/fcre-2021-11-01-test_run.nc
start_datetime: 2021-10-31 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-11-01 00:00:00
forecast_horizon: 16.0
sim_name: test_run
forecast_site: fcre
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
forecast_site: fcre
